name: Dynamic matrix


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dynamic-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: "touch foo bar biz"
      - run: "ls -ltr foo bar biz"
      - run: "jq --help"