name: Dynamic matrix


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      files_json: ${{ steps.list-files.outputs.files_json }}
    steps:
      - run: "touch foo bar biz"
      - id: list-files
        run: |
          FILES_ARRAY=($(ls))
          FILES_JSON=$(echo "${FILES_ARRAY[@]}" | jq -R -s -c 'split(" ")')
          echo "files_json=${FILES_JSON}" >> $GITHUB_OUTPUT
  dynamic-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.generate-matrix.outputs.files_json) }}
    steps:
      - name: Show file
        run: echo ${{ matrix.file }}
      