name: Dynamic matrix


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: "touch foo bar biz"
      - name: run
        run: |
          ls -ltr
          FILES=$(ls)
          FILES_ARRAY=($FILES)
          FILES_JSON=$(echo "${FILES_ARRAY[@]}" | jq -R -s -c 'split(" ")')
          echo "::set-output name=files_json::${FILES_JSON}"
  dynamic-matrix:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.generate-matrix.outputs.files_json) }}
    steps:
      - name: Show file
        run: echo "File: ${{ matrix.file }}"
      